# WordPress configuration
wordpress:
  image:
    repository: yourusername/wordpress
    tag: latest
  persistence:
    existingClaim: wordpress-pvc

# MySQL configuration
mysql:
  image:
    repository: yourusername/mysql
    tag: latest
  persistence:
    existingClaim: mysql-pvc

# Nginx configuration
nginx:
  image:
    repository: yourusername/nginx-openresty
    tag: latest

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: wordpress.example.com
      paths:
        - path: /
          pathType: Prefix

# ServiceAccount configuration
serviceAccount:
  create: true
  name: ""
  automount: true

# Persistence configuration
persistence:
  enabled: true

# Resource configuration
resources: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Replica count
replicaCount: 1

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Any additional configurations your chart might need