apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: wordpress
  endpoints:
  - port: "http"  # Port specified as string
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: "http"  # Port specified as string
