apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-wordpress
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wordpress-chart.selectorLabels" . | nindent 6 }}
      app: wordpress
  template:
    metadata:
      labels:
        {{- include "wordpress-chart.selectorLabels" . | nindent 8 }}
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.wordpress.persistence.existingClaim }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-mysql
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wordpress-chart.selectorLabels" . | nindent 6 }}
      app: mysql
  template:
    metadata:
      labels:
        {{- include "wordpress-chart.selectorLabels" . | nindent 8 }}
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "abc123"  # Set a secure root password here
            - name: MYSQL_DATABASE
              value: "database1"   # Optionally set a default database name
            - name: MYSQL_USER
              value: "yash"        # Optionally set a custom MySQL user
            - name: MYSQL_PASSWORD
              value: "abc1234"        # Optionally set a password for the custom MySQL user
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.persistence.existingClaim }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-nginx
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wordpress-chart.selectorLabels" . | nindent 6 }}
      app: nginx
  template:
    metadata:
      labels:
        {{- include "wordpress-chart.selectorLabels" . | nindent 8 }}
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: 80
