apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-nginx-config
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        upstream wordpress {
            server {{ include "wordpress-chart.fullname" . }}-wordpress:80;
        }
        server {
            listen 80;
            server_name wordpress.local;
            location / {
                proxy_pass http://wordpress;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /nginx_status {
                stub_status on;
                access_log off;
                allow 127.0.0.1;
                deny all;
            }
            location /hello {
                content_by_lua_block {
                    ngx.say("Hello from OpenResty!")
                }
            }
        }
    }