wordpress:
  image:
    repository: yashingole1000/wordpress
    tag: v1
  persistence:
    existingClaim: wordpress-pvc
  service:
    port: 80

mysql:
  image:
    repository: yashingole1000/mysql
    tag: v1
  persistence:
    enabled: true
    existingClaim: wordpress-pvc
    accessMode: ReadWriteMany
    size: 5Gi
  service:
    port: 3306
  rootPassword: "abc123"  # Set a secure root password
  database: "database1"   # Optionally set a default database name
  user: "yash"            # Optionally set a custom MySQL user
  password: "abc1234"     # Optionally set a password for the custom MySQL user

nginx:
  image:
    repository: yashingole1000/nginx
    tag: v3
  service:
    port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
