wordpress:
  image:
    repository: yashingole1000/wordpress
    tag: v1
  persistence:
    existingClaim: wordpress-pvc
  service:
    port: 80

mysql:
  image:
    repository: yashingole1000/mysql
    tag: v1
  persistence:
    enabled: true
    existingClaim: wordpress-pvc
    accessMode: ReadWriteMany
    size: 5Gi
  service:
    port: 3306
  configurationFiles:
    my.cnf: |
      [mysqld]
      explicit_defaults_for_timestamp=1
  initContainers:
    - name: init-mysql
      image: busybox
      command:
        - sh
        - -c
        - "rm -rf /var/lib/mysql/*"
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

nginx:
  image:
    repository: yashingole1000/nginx
    tag: v2
  service:
    port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
