# Global persistence configuration
persistence:
  enabled: true
  storageClassName: efs-sc
  provisioner: efs.csi.aws.com
  csiDriver: efs.csi.aws.com
  volumeHandle: fs-0c62dbc24fcc78163
  size: 5Gi

# WordPress configuration
wordpress:
  image:
    repository: yashingole1000/wordpress
    tag: v1
  service:
    port: 80

# MySQL configuration
mysql:
  image:
    repository: yashingole1000/mysql
    tag: v1
  service:
    port: 3306
  rootPassword: "abc123"  # Set a secure root password
  database: "database1"   # Optionally set a default database name
  user: "yash"            # Optionally set a custom MySQL user
  password: "abc1234"     # Optionally set a password for the custom MySQL user

# Nginx configuration
nginx:
  image:
    repository: yashingole1000/nginx
    tag: v3
  service:
    port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false

# Prometheus configuration
prometheus:
  enabled: true

# Grafana configuration
grafana:
  enabled: true
  adminPassword: "changeme"