wordpress:
  image:
    repository: yashingole1000/wordpress
    tag: v1
  persistence:
    existingClaim: wordpress-pvc
  service:
    port: 80

mysql:
  image:
    repository: yashingole1000/mysql
    tag: v1
  persistence:
    enabled: true
    existingClaim: mysql-pvc  # Ensure this matches the PVC name for MySQL
    accessMode: ReadWriteMany
    size: 5Gi
  service:
    port: 3306

nginx:
  image:
    repository: yashingole1000/nginx
    tag: v2
  service:
    name: {{ include "wordpress-chart.fullname" . }}-nginx
    port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
