---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0c014f5b3532100e8
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi


 