{{- if .Values.persistence.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClassName }}
provisioner: {{ .Values.persistence.provisioner }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-pv
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  csi:
    driver: {{ .Values.persistence.csiDriver }}
    volumeHandle: {{ .Values.persistence.volumeHandle }}

---

   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: {{ include "wordpress-chart.fullname" . }}-wordpress-pvc
   spec:
     accessModes:
       - ReadWriteMany
     storageClassName: {{ .Values.persistence.storageClassName }}
     resources:
       requests:
         storage: {{ .Values.persistence.size }}
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: {{ include "wordpress-chart.fullname" . }}-mysql-pvc
   spec:
     accessModes:
       - ReadWriteMany
     storageClassName: {{ .Values.persistence.storageClassName }}
     resources:
       requests:
         storage: {{ .Values.persistence.size }}
   