apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/mysql
    server: fs-0c62dbc24fcc78163.efs.us-west-2.amazonaws.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: {{ .Values.wordpress.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/wordpress
    server: fs-0c62dbc24fcc78163.efs.us-west-2.amazonaws.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
