apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/mysql
    server: 192.168.105.89  # Replace with the IP address we found
    mountOptions:
      - nfsvers=4.1
      - rsize=1048576
      - wsize=1048576
      - hard
      - timeo=600
      - retrans=2
      - noresvport
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: {{ .Values.wordpress.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/wordpress
    server: 192.168.105.89  # Replace with the IP address we found
    mountOptions:
      - nfsvers=4.1
      - rsize=1048576
      - wsize=1048576
      - hard
      - timeo=600
      - retrans=2
      - noresvport
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}