apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.wordpress.dbHost }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.wordpress.dbPasswordSecret }}  # Use plain text password here
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
