FROM openresty/openresty:alpine

RUN apk add --no-cache gcc libtool make pcre-dev \
    && mkdir -p /usr/local/src \
    && cd /usr/local/src \
    && wget https://openresty.org/download/openresty-1.19.9.1.tar.gz \
    && tar xzf openresty-1.19.9.1.tar.gz \
    && cd openresty-1.19.9.1 \
    && ./configure --prefix=/opt/openresty --with-pcre-jit --with-ipv6 --without-http_redis2_module --with-http_iconv_module --with-http_postgres_module -j8 \
    && make -j8 \
    && make install


